# Generated by Django 2.1 on 2018-11-25 19:58

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailimages', '0021_image_file_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnersPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('title_es', models.CharField(blank=True, max_length=255)),
                ('sub_title_en', models.CharField(blank=True, max_length=255)),
                ('sub_title_es', models.CharField(blank=True, max_length=255)),
                ('intro_en', wagtail.core.fields.RichTextField(blank=True)),
                ('intro_es', wagtail.core.fields.RichTextField(blank=True)),
                ('colour', colorfield.fields.ColorField(default='#6c6c1c', max_length=18)),
                ('seo_title_en', models.TextField(blank=True)),
                ('seo_title_es', models.TextField(blank=True)),
                ('seo_description_en', models.TextField(blank=True)),
                ('seo_description_es', models.TextField(blank=True)),
                ('cover_image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
