# Generated by Django 2.0.9 on 2018-10-06 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_snippets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codesnippet',
            old_name='name',
            new_name='title',
        ),
    ]
