# Generated by Django 2.0.9 on 2018-10-08 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_snippets', '0002_auto_20181006_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codesnippet',
            name='code',
        ),
    ]
