# Generated by Django 2.0.9 on 2018-10-08 12:56

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('code_snippets', '0003_remove_codesnippet_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesnippet',
            name='code_samples',
            field=wagtail.core.fields.StreamField([('code', wagtail.core.blocks.RawHTMLBlock())], blank=True),
        ),
    ]
