# Generated by Django 2.0.7 on 2018-08-02 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20180802_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitehighlight',
            old_name='highlights',
            new_name='highlight',
        ),
    ]
