# Generated by Django 2.0.7 on 2018-08-03 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20180802_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitehighlight',
            old_name='highlight',
            new_name='highs',
        ),
    ]
