# Generated by Django 2.0.7 on 2018-08-03 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20180803_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitehighlight',
            name='highlight_ptr',
        ),
        migrations.RemoveField(
            model_name='sitehighlight',
            name='highs',
        ),
        migrations.DeleteModel(
            name='SiteHighlight',
        ),
    ]
