# Generated by Django 2.0.7 on 2018-08-03 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_auto_20180803_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialmedia',
            old_name='logo',
            new_name='icon',
        ),
    ]
