# Generated by Django 2.0.7 on 2018-08-03 13:39

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20180803_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='colour',
            field=colorfield.fields.ColorField(default='#1c1c1c', max_length=18),
        ),
    ]
