# Generated by Django 2.0.7 on 2018-08-03 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0020_add-verbose-name'),
        ('article', '0011_articlepagegalleryimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepagegalleryimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='articlepagegalleryimage',
            name='page',
        ),
        migrations.AddField(
            model_name='articlepage',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.DeleteModel(
            name='ArticlePageGalleryImage',
        ),
    ]
