# Generated by Django 2.0.7 on 2018-08-06 12:05

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0019_auto_20180806_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlepagetag',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='articlepagetag',
            name='tag',
        ),
        migrations.AddField(
            model_name='articlepage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='article.ArticleCategory'),
        ),
        migrations.DeleteModel(
            name='ArticlePageTag',
        ),
    ]
