# Generated by Django 2.0.7 on 2018-08-06 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0020_auto_20180806_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlepage',
            old_name='categories',
            new_name='category',
        ),
    ]
