# Generated by Django 2.0.7 on 2018-08-06 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0021_auto_20180806_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlepage',
            old_name='category',
            new_name='categories',
        ),
    ]
