# Generated by Django 2.0.7 on 2018-08-09 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0025_auto_20180809_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='highlight',
            name='name',
        ),
    ]
