# Generated by Django 2.0.7 on 2018-08-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0027_auto_20180809_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articletips',
            old_name='front_text',
            new_name='front_text_en',
        ),
        migrations.AddField(
            model_name='articletips',
            name='front_text_es',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
