# Generated by Django 2.0.7 on 2018-08-13 08:10

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0029_auto_20180813_0759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interactiontype',
            old_name='default_description',
            new_name='default_description_en',
        ),
        migrations.RemoveField(
            model_name='footerlink',
            name='name',
        ),
        migrations.RemoveField(
            model_name='interactiontype',
            name='name',
        ),
        migrations.AddField(
            model_name='footerlink',
            name='name_en',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='footerlink',
            name='name_es',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='interactiontype',
            name='default_description_es',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='interactiontype',
            name='name_en',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='interactiontype',
            name='name_es',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
