# Generated by Django 2.0.7 on 2018-08-13 08:55

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0030_auto_20180813_0810'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleSectionEN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('section_name', models.CharField(blank=True, max_length=50)),
                ('section_content', wagtail.core.fields.RichTextField(blank=True)),
                ('section_addons', wagtail.core.fields.StreamField([('effects', wagtail.core.blocks.StructBlock([('positive_effects', wagtail.core.blocks.ListBlock(wagtail.core.blocks.CharBlock())), ('neutral_effects', wagtail.core.blocks.ListBlock(wagtail.core.blocks.CharBlock())), ('negative_effects', wagtail.core.blocks.ListBlock(wagtail.core.blocks.CharBlock()))])), ('content', wagtail.core.blocks.RichTextBlock(blank=True)), ('table_of_three', wagtail.core.blocks.StructBlock([('title_1', wagtail.core.blocks.CharBlock(blank=True, max_length=10)), ('content_1', wagtail.core.blocks.RichTextBlock(blank=True)), ('title_2', wagtail.core.blocks.CharBlock(blank=True, max_length=10)), ('content_2', wagtail.core.blocks.RichTextBlock(blank=True)), ('title_3', wagtail.core.blocks.CharBlock(blank=True, max_length=10)), ('content_3', wagtail.core.blocks.RichTextBlock(blank=True))])), ('interactions', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('drug_name', wagtail.core.blocks.CharBlock(blank=True, max_length=13)), ('interaction_type', wagtail.snippets.blocks.SnippetChooserBlock('article.InteractionType')), ('description', wagtail.core.blocks.RichTextBlock(blank=True))]))), ('brain_tip', wagtail.core.blocks.StructBlock([('click_the_brain_text', wagtail.core.blocks.CharBlock(blank=True, default='Click the brain for neuro-info!', max_length=255)), ('content', wagtail.core.blocks.RichTextBlock(blank=True))]))], blank=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleSectionES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('section_name', models.CharField(blank=True, max_length=50)),
                ('section_content', wagtail.core.fields.RichTextField(blank=True)),
                ('section_addons', wagtail.core.fields.StreamField([('effects', wagtail.core.blocks.StructBlock([('positive_effects', wagtail.core.blocks.ListBlock(wagtail.core.blocks.CharBlock())), ('neutral_effects', wagtail.core.blocks.ListBlock(wagtail.core.blocks.CharBlock())), ('negative_effects', wagtail.core.blocks.ListBlock(wagtail.core.blocks.CharBlock()))])), ('content', wagtail.core.blocks.RichTextBlock(blank=True)), ('table_of_three', wagtail.core.blocks.StructBlock([('title_1', wagtail.core.blocks.CharBlock(blank=True, max_length=10)), ('content_1', wagtail.core.blocks.RichTextBlock(blank=True)), ('title_2', wagtail.core.blocks.CharBlock(blank=True, max_length=10)), ('content_2', wagtail.core.blocks.RichTextBlock(blank=True)), ('title_3', wagtail.core.blocks.CharBlock(blank=True, max_length=10)), ('content_3', wagtail.core.blocks.RichTextBlock(blank=True))])), ('interactions', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('drug_name', wagtail.core.blocks.CharBlock(blank=True, max_length=13)), ('interaction_type', wagtail.snippets.blocks.SnippetChooserBlock('article.InteractionType')), ('description', wagtail.core.blocks.RichTextBlock(blank=True))]))), ('brain_tip', wagtail.core.blocks.StructBlock([('click_the_brain_text', wagtail.core.blocks.CharBlock(blank=True, default='Click the brain for neuro-info!', max_length=255)), ('content', wagtail.core.blocks.RichTextBlock(blank=True))]))], blank=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleTipsEN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('front_text', models.CharField(blank=True, max_length=16)),
                ('back_text', models.CharField(blank=True, max_length=175)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArticleTipsES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('front_text', models.CharField(blank=True, max_length=16)),
                ('back_text', models.CharField(blank=True, max_length=175)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='articlesection',
            name='article',
        ),
        migrations.RemoveField(
            model_name='articletips',
            name='tips',
        ),
        migrations.RenameField(
            model_name='articlepage',
            old_name='intro',
            new_name='intro_en',
        ),
        migrations.RenameField(
            model_name='articlepage',
            old_name='sub_title',
            new_name='sub_title_en',
        ),
        migrations.AddField(
            model_name='articlepage',
            name='intro_es',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='sub_title_es',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='title_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='title_es',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='ArticleSection',
        ),
        migrations.DeleteModel(
            name='ArticleTips',
        ),
        migrations.AddField(
            model_name='articletipses',
            name='tips',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='things_to_take_es', to='article.ArticlePage'),
        ),
        migrations.AddField(
            model_name='articletipsen',
            name='tips',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='things_to_take_en', to='article.ArticlePage'),
        ),
        migrations.AddField(
            model_name='articlesectiones',
            name='article',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections_es', to='article.ArticlePage'),
        ),
        migrations.AddField(
            model_name='articlesectionen',
            name='article',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections_en', to='article.ArticlePage'),
        ),
    ]
