# Generated by Django 2.0.7 on 2018-08-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0037_auto_20180813_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interactiontype',
            name='default_description_en',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='interactiontype',
            name='default_description_es',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
