# Generated by Django 2.0.7 on 2018-08-21 15:02

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0041_auto_20180814_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='interactiontype',
            name='colour',
            field=colorfield.fields.ColorField(default='#6c6c6c', max_length=18),
        ),
    ]
