# Generated by Django 2.0.7 on 2018-09-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0044_auto_20180822_1136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footerlink',
            name='link',
        ),
        migrations.AddField(
            model_name='footerlink',
            name='link_en',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='footerlink',
            name='link_es',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='name_es',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='link_en',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='link_es',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='name_es',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
