# Generated by Django 2.0.9 on 2018-10-06 09:57

import code_snippets.models
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('article', '0050_auto_20181006_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSnippet',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='intro_extras',
            field=wagtail.core.fields.StreamField([('code_snippets', code_snippets.models.CodeSnippetBlock('code_snippets.CodeSnippet'))], blank=True),
        ),
        migrations.AddField(
            model_name='codesnippet',
            name='article',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_snippets', to='article.ArticlePage'),
        ),
    ]
