# Generated by Django 2.0.9 on 2018-10-06 10:32

import code_snippets.models
from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('article', '0051_auto_20181006_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codesnippet',
            name='article',
        ),
        migrations.RemoveField(
            model_name='codesnippet',
            name='page_ptr',
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='intro_extras',
            field=wagtail.core.fields.StreamField([('code_snippet', code_snippets.models.CodeSnippetBlock('code_snippets.CodeSnippet'))], blank=True),
        ),
        migrations.DeleteModel(
            name='CodeSnippet',
        ),
    ]
