# Generated by Django 2.0.9 on 2018-10-09 14:52

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0053_auto_20181006_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleconstants',
            name='campaign_caption_en',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='articleconstants',
            name='campaign_caption_es',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
