# Generated by Django 2.0.9 on 2018-10-11 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0054_auto_20181009_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='search_description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='search_description_es',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='seo_title_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='seo_title_es',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='slug_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='slug_es',
            field=models.TextField(blank=True),
        ),
    ]
