# Generated by Django 2.0.9 on 2018-10-12 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0056_auto_20181012_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlepage',
            old_name='search_description_en',
            new_name='seo_description_en',
        ),
        migrations.RenameField(
            model_name='articlepage',
            old_name='search_description_es',
            new_name='seo_description_es',
        ),
    ]
