# Generated by Django 2.1 on 2018-11-30 11:33

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0060_auto_20181130_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleconstants',
            name='cookie_banner_en',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='articleconstants',
            name='cookie_banner_es',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
