# Generated by Django 2.1 on 2019-03-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0066_teammemberdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammemberdetails',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
