# Generated by Django 2.1.5 on 2019-04-14 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0072_auto_20190412_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecategory',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='categories',
        ),
        migrations.DeleteModel(
            name='ArticleCategory',
        ),
    ]
