# Generated by Django 2.0.9 on 2018-10-08 20:43

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181008_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='colour',
            field=colorfield.fields.ColorField(default='#bbcee5', max_length=18),
        ),
    ]
