# Generated by Django 2.0.9 on 2018-10-09 08:50

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20181008_2049'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPageLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'article categories',
            },
        ),
        migrations.AddField(
            model_name='blogpage',
            name='language',
            field=modelcluster.fields.ParentalManyToManyField(to='blog.BlogPageLanguage'),
        ),
    ]
