# Generated by Django 2.0.9 on 2018-10-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20181009_0850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpagelanguage',
            options={'verbose_name_plural': 'blog languages'},
        ),
        migrations.AddField(
            model_name='blogpagelanguage',
            name='lang_code',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
