# Generated by Django 2.0.9 on 2018-10-14 09:45

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailimages', '0021_image_file_hash'),
        ('blog', '0006_auto_20181009_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('organisation_name', models.TextField()),
                ('publication_date', models.DateField()),
                ('author', models.TextField()),
                ('article_title', models.TextField()),
                ('article_link', models.URLField()),
                ('summary', wagtail.core.fields.RichTextField()),
                ('organisation_logo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
