# Generated by Django 2.0.9 on 2018-10-14 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_mention'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mention',
            name='article_title',
        ),
    ]
