# Generated by Django 2.0.9 on 2018-10-14 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20181014_1111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpage',
            old_name='date',
            new_name='publication_date',
        ),
        migrations.AlterField(
            model_name='mention',
            name='organisation_name',
            field=models.TextField(),
        ),
    ]
