# Generated by Django 2.1.5 on 2019-08-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190726_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='is_published_en',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='blogindexpage',
            name='is_published_es',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
