# Generated by Django 2.1 on 2018-11-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customimage',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
