# Generated by Django 2.1 on 2018-11-26 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20181125_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customimage',
            old_name='URL',
            new_name='link',
        ),
    ]
