# Generated by Django 2.0.7 on 2018-08-07 07:56

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexBlurb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('section_name', models.CharField(blank=True, max_length=50)),
                ('section_content', wagtail.core.fields.StreamField([('text', wagtail.core.blocks.RichTextBlock()), ('partners', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(blank=True, max_length=25)), ('link', wagtail.core.blocks.CharBlock(blank=True, max_length=255))])))], blank=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.AddField(
            model_name='indexblurb',
            name='article',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_sections', to='home.HomePage'),
        ),
    ]
