# Generated by Django 2.0.7 on 2018-08-07 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180807_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='title_tip_drugs',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_tip_me',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
