# Generated by Django 2.0.7 on 2018-08-23 09:20

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180807_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexBlurbEN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('section_name', models.CharField(blank=True, max_length=50)),
                ('section_content', wagtail.core.fields.StreamField([('text', wagtail.core.blocks.RichTextBlock()), ('partners', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(blank=True, max_length=25)), ('link', wagtail.core.blocks.CharBlock(blank=True, max_length=255)), ('logo', wagtail.images.blocks.ImageChooserBlock())])))], blank=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndexBlurbES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('section_name', models.CharField(blank=True, max_length=50)),
                ('section_content', wagtail.core.fields.StreamField([('text', wagtail.core.blocks.RichTextBlock()), ('partners', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(blank=True, max_length=25)), ('link', wagtail.core.blocks.CharBlock(blank=True, max_length=255)), ('logo', wagtail.images.blocks.ImageChooserBlock())])))], blank=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='indexblurb',
            name='article',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='title_tip_drugs',
            new_name='title_lead_en',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='title_tip_me',
            new_name='title_lead_es',
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_tip_drugs_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_tip_drugs_es',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_tip_me_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_tip_me_es',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='IndexBlurb',
        ),
        migrations.AddField(
            model_name='indexblurbes',
            name='article',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_sections_es', to='home.HomePage'),
        ),
        migrations.AddField(
            model_name='indexblurben',
            name='article',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_sections_en', to='home.HomePage'),
        ),
    ]
