# Generated by Django 2.0.7 on 2018-08-23 14:23

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180823_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='title_lead_en',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='title_lead_es',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
