# Generated by Django 2.0.9 on 2018-10-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20180823_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='title_lead_en',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='title_lead_es',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
