# Generated by Django 2.1.5 on 2019-04-26 13:54

import code_snippets.models
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20181006_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexblurben',
            name='section_content',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.RichTextBlock()), ('partners', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(blank=True, max_length=25)), ('link', wagtail.core.blocks.CharBlock(blank=True, max_length=255)), ('logo', wagtail.images.blocks.ImageChooserBlock())]))), ('code_snippet', code_snippets.models.CodeSnippetBlock('code_snippets.CodeSnippet'))], blank=True),
        ),
        migrations.AlterField(
            model_name='indexblurbes',
            name='section_content',
            field=wagtail.core.fields.StreamField([('text', wagtail.core.blocks.RichTextBlock()), ('partners', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(blank=True, max_length=25)), ('link', wagtail.core.blocks.CharBlock(blank=True, max_length=255)), ('logo', wagtail.images.blocks.ImageChooserBlock())]))), ('code_snippet', code_snippets.models.CodeSnippetBlock('code_snippets.CodeSnippet'))], blank=True),
        ),
    ]
